import { HomeCon } from '@/features/home/UI/Container/HomeCon';
import { Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home:NextPage = () => {
  return (
    <>
      <Head>
        <title>被写体マッチング</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCon/>
    </>
  );
};

export default Home;